#!/usr/bin/env bash
# Provision Umami: create the tracked website and generate www/analytics.js
# Idempotent: safe to run multiple times.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# ── Load .env ──────────────────────────────────────────────────────────
ENV_FILE="$ROOT_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  set -o allexport
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +o allexport
fi

# ── Require mandatory variables ────────────────────────────────────────
: "${UMAMI_INTERNAL_URL:?UMAMI_INTERNAL_URL is not set in .env}"
: "${UMAMI_PUBLIC_URL:?UMAMI_PUBLIC_URL is not set in .env}"
: "${DOMAIN:?DOMAIN is not set in .env}"
: "${UMAMI_ADMIN_PASSWORD:?UMAMI_ADMIN_PASSWORD is not set in .env}"

ANALYTICS_OUT="$ROOT_DIR/www/analytics.js"

# ── Wait for Umami ─────────────────────────────────────────────────────
echo "Waiting for Umami at $UMAMI_INTERNAL_URL ..."
for i in $(seq 1 30); do
  if curl -sf "$UMAMI_INTERNAL_URL/api/heartbeat" > /dev/null 2>&1; then
    break
  fi
  if [[ $i -eq 30 ]]; then
    echo "ERROR: Umami did not respond after 60s. Is 'make up' running?"
    exit 1
  fi
  sleep 2
done
echo "Umami is up."

# ── Authenticate (try new password first, fallback to default) ─────────
_login() {
  local password="$1"
  python3 - <<PYEOF
import json, urllib.request, urllib.error, sys
try:
    req = urllib.request.Request(
        "$UMAMI_INTERNAL_URL/api/auth/login",
        data=json.dumps({"username": "admin", "password": "$password"}).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as r:
        body = json.load(r)
        print(body["token"])
        print(body["user"]["id"])
except urllib.error.HTTPError:
    sys.exit(1)
PYEOF
}

TOKEN=""
USER_ID=""
PASSWORD_CHANGED=false

echo "Logging in..."
if output=$(_login "$UMAMI_ADMIN_PASSWORD" 2>/dev/null); then
  TOKEN=$(echo "$output" | head -1)
  USER_ID=$(echo "$output" | tail -1)
  PASSWORD_CHANGED=true
elif output=$(_login "umami" 2>/dev/null); then
  TOKEN=$(echo "$output" | head -1)
  USER_ID=$(echo "$output" | tail -1)
else
  echo "ERROR: login failed with both default and configured passwords."
  echo "  Check UMAMI_ADMIN_PASSWORD in .env"
  exit 1
fi

# ── Change default password (only on first run) ────────────────────────
if [[ "$PASSWORD_CHANGED" == false ]]; then
  if [[ "$UMAMI_ADMIN_PASSWORD" == "change-me-in-production" ]]; then
    echo "WARNING: UMAMI_ADMIN_PASSWORD is still the default placeholder."
    echo "  Set a real password in .env before deploying to production."
  else
    echo "Changing admin password..."
    python3 - <<PYEOF
import json, urllib.request
req = urllib.request.Request(
    "$UMAMI_INTERNAL_URL/api/users/$USER_ID",
    data=json.dumps({"password": "$UMAMI_ADMIN_PASSWORD"}).encode(),
    headers={"Content-Type": "application/json", "Authorization": "Bearer $TOKEN"},
    method="POST",
)
with urllib.request.urlopen(req) as r:
    pass
print("Password updated.")
PYEOF
  fi
fi

# ── Find or create website ─────────────────────────────────────────────
echo "Looking up website for domain '$DOMAIN'..."
WEBSITE_ID=$(python3 - <<PYEOF
import json, urllib.request, sys

# List all websites (Umami paginates at 100 by default)
req = urllib.request.Request(
    "$UMAMI_INTERNAL_URL/api/websites?pageSize=100",
    headers={"Authorization": "Bearer $TOKEN"},
)
with urllib.request.urlopen(req) as r:
    data = json.load(r)

websites = data.get("data", data) if isinstance(data, dict) else data
match = next((w for w in websites if w.get("domain") == "$DOMAIN"), None)
if match:
    print(match["id"])
else:
    print("")
PYEOF
)

if [[ -n "$WEBSITE_ID" ]]; then
  echo "Website already exists (id: $WEBSITE_ID)."
else
  echo "Creating website..."
  WEBSITE_ID=$(python3 - <<PYEOF
import json, urllib.request
req = urllib.request.Request(
    "$UMAMI_INTERNAL_URL/api/websites",
    data=json.dumps({"name": "You", "domain": "$DOMAIN"}).encode(),
    headers={"Content-Type": "application/json", "Authorization": "Bearer $TOKEN"},
)
with urllib.request.urlopen(req) as r:
    body = json.load(r)
print(body["id"])
PYEOF
)
  echo "Website created (id: $WEBSITE_ID)."
fi

# ── Write www/analytics.js ─────────────────────────────────────────────
cat > "$ANALYTICS_OUT" <<JSEOF
// Auto-generated by scripts/provision.sh — do not edit
// Umami analytics for $DOMAIN (website id: $WEBSITE_ID)
(function () {
  var s = document.createElement('script');
  s.defer = true;
  s.src = '$UMAMI_PUBLIC_URL/script.js';
  s.setAttribute('data-website-id', '$WEBSITE_ID');
  s.setAttribute('data-host-url', '$UMAMI_PUBLIC_URL');
  document.head.appendChild(s);
})();
JSEOF

echo ""
echo "Done."
echo "  analytics.js  -> $ANALYTICS_OUT"
echo "  Umami dashboard -> $UMAMI_INTERNAL_URL (admin / your password)"
echo ""
echo "    Next: in nginx-proxy-manager:"
echo "      Proxy host: $DOMAIN → port 8200 (Caddy)"
echo ""
echo "      Custom location for Umami analytics:"
echo "        /analytics/script.js  →  http://PI_IP:8300/script.js   (exact match, bypasses BASE_PATH)"
echo "        /analytics            →  http://PI_IP:8300              (admin UI — BASE_PATH=/analytics handles routing)"
echo ""
echo "      In NPM Advanced config for the /analytics/script.js location, add:"
echo "        proxy_pass http://PI_IP:8300/script.js;"
