name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Raspberry Pi
    runs-on: [self-hosted, linux, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: cd ~/you && make deploy
